# This is a basic workflow to help you get started with Actions

name: Create lxgw FontModule

# Controls when the workflow will run
on:
  # 手动运行
  workflow_dispatch:
#UI界面
      inputs:
        logLevel:
          description: 'Log level'
          required: true
          default: 'warning'
          type: choice
          options:
          - info
          - warning
          - debug
        tags:
          description: 'Test scenario tags'
          required: false
          type: boolean
        environment:
          description: 'Environment to run tests against'
          type: environment
          required: true

# 任务
jobs:
  # 创建模块
  创建模块:
    runs-on: 1
     echo Add other actions to build,
     echo test, and deploy your project.
